spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jpa_sql_exercise
    username: postgres
    password: 1234
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate.ddl-auto: update
      hibernate.dialect: org.hibernate.dialect.PostgreSQL10Dialect
#  sql:
#    init:
#      mode: always